<?
$b_fo='#555555';
$li_fo='#cc66cc';
$vi_fo='cc66cc';
$ac_fo='';
$pic_number='cc33aa';
$comm_ad_namecol='';
$comm_ad_datecol='#C9C9C9';
$comm_ad_datebgcol='';
$comm_ad_fontcol='cc66cc';
$kd_memocol='cc66cc';
$kd_seccol='cc33aa';
$kd_morecol='cc66cc';
$reply_text='';
$replt_text='cc33aa';
$kd_ipcol='#FFFFFF';
$comm_cu_namecol='';
$comm_cu_datecol='#C9C9C9';
$comm_cu_fontcol='';
$co_w_txfontcol='';
$co_w_fontcol='';
$co_w_subcol='';
$beu_te_fontcol='';
$beu_bt_fontcol='191919';
$commore='';
?>
