<?
$bgcol='#000000';
$alltb_bgc='';
$alltb_borc='#efefef';
$toptb_bgc='';
$menutb_bgc='';
$menutb_borc='';
$maintb_bgc='';
$maintb_borc='';
$logtb_bgc='#ffffff';
$logtb_borc='#efefef';
$pictb_bgc='';
$comtb_bgc='';
$comm_adbgcol='';
$comm_cuscol='';
$repl_bgcol='';
$co_w_tb_bordercol='';
$co_w_tbcol='';
$co_w_textbox='';
$co_m_textbox='';
$co_w_submit='cc66cc';
$beu_te_bgcol='191919';
$beu_te_bordercol='#F0F0F0';
$beu_bt_col='#191919';
$beu_bt_bodercol='#ffffff';
?>
